version: '3.8'

services:
    dev:
        container_name: nestjs_api_dev
        image: nestjs-api-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    mongodb:
        image: mongo:latest
        restart: always
        ports:
        - 27017:27017
        volumes:
        - data:/data/db
        networks:
        - internal

    mongo-express:
        image: mongo-express
        restart: always
        ports:
        - 8081:8081
        environment: 
            ME_CONFIG_MONGODB_URL: mongodb://mongodb/airline
        networks:
        - internal
networks:
    internal:
    nesjs-network:

volumes:
  data: