version: '3.8'

services:
    booking:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            SERVICES: booking
        depends_on:
             - mongodb
        networks:
          - internal
    mongodb:
        image: mongo:latest
        restart: always
        ports:
        - 27017:27017
        volumes:
        - data:/data/db
        environment:
            - MONGODB_DATABASE="airline"
        networks:
        - internal

    mongo-express:
        image: mongo-express
        restart: always
        ports:
        - 8081:8081
        environment: 
            ME_CONFIG_MONGODB_URL: mongodb://mongodb/airline
        networks:
        - internal
networks:
    internal:

volumes:
  data: